services:
  naradio:
    image: ghcr.io/bjoernellens1/na-radio-standalone:cuda
    build:
      context: .
      args:
        TARGET_ARCH: nvidia
    # privileged: true
    ports:
      - "5000:5000"
      - "5443:5443"
    devices:
      - nvidia.com/gpu=all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
