services:
  naradio:
    image: ghcr.io/bjoernellens1/na-radio-standalone:cuda
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
